// @include "./sacred-lotus-final/core.wgsl"
// @include "./sacred-lotus-final/background-atmosphere.wgsl"
// @include "./sacred-lotus-final/lotus-symbol.wgsl"
// @include "./sacred-lotus-final/energy-ribbons.wgsl"
// @include "./sacred-lotus-final/post-figure-composition.wgsl"
